#! /usr/bin/env python

import sys

from fabric2 import ThreadingGroup

latest_version = "model-002357.hd5"

def update_host(conn):
    """
    Copy the latest model file, replace the version in the service unit and restart the service
    """

    conn.put(latest_version)
    conn.sudo(f"sed -i -e 's/model-[0-9]+\.hd5/{latest_version}/g' /etc/systemd/system/smartbird.service")
    conn.sudo("systemctl daemon-reload && systemctl restart smartbird")

if __name__ == "__main__":

    hosts = sys.argv[1:]

    all_hosts_parallel = ThreadingGroup(*hosts)

    ps = all_hosts_parallel.run(f"ps aux | grep -V grep  | grep {latest_version}", warn=True, hide=True)
    hosts_to_update = [conn for conn,result in ps.items() if not result.ok]

    for conn in hosts_to_update:
        update_host(conn)
